// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 MasakatsuFunaki
//
// Part of VN_TRANSLATE.  Licensed under GPL-3.0-or-later; see LICENSE.
// Not licensed for use as training data for machine learning or generative
// AI systems; text and data mining rights are reserved.  See NOTICE.

// Self-contained CatSystem2 archive (KIF) and scene script (CST) parser.
//
// Only the read side is implemented; this pipeline does NOT modify scene.int
// -- translation happens at runtime via the proxy DLL.
//
// Reference: https://github.com/trigger-segfault/catsystem-py
#pragma once

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

#include "common/util.h"

namespace ama::cs2 {

// ---- MT19937 ---------------------------------------------------------------

// First 32-bit word generated by MT19937 seeded with `seed`.  CatSystem2 uses
// it to derive the Blowfish key, so only the first word is ever needed: the
// state words that feed it are computed inline instead of running a full
// generator.
std::uint32_t mt_genrand(std::uint32_t seed);

// ---- KIF archive (.int) ----------------------------------------------------
//
// Header: 4-byte signature "KIF\0" + uint32 entry_count
// Entries (v2): 64-byte name (cp932, null-padded) + uint32 offset +
//   uint32 length = 72 bytes per entry.
// The first entry is "__key__.dat" -- its `length` field is the MT19937 seed
// used to derive the Blowfish key.  All subsequent entries have their
// (offset+index, length) pair Blowfish-decrypted as an LR block, and their
// payloads are Blowfish-decrypted 8 bytes at a time.

struct KifEntry {
    std::string name;
    std::uint32_t offset = 0;
    std::uint32_t length = 0;
};

class KifArchive {
public:
    explicit KifArchive(const std::string& path);
    ~KifArchive();
    KifArchive(const KifArchive&) = delete;
    KifArchive& operator=(const KifArchive&) = delete;

    const std::vector<KifEntry>& entries() const { return entries_; }

    // Decrypt and return the raw bytes of one entry.
    Bytes extract(const KifEntry& entry) const;

private:
    struct Cipher;
    std::string path_;
    std::vector<KifEntry> entries_;
    std::unique_ptr<Cipher> cipher_;
};

// ---- CatScene script (.cst) ------------------------------------------------
//
// File header (16 bytes): "CatScene" + uint32 compressed_len +
// uint32 original_len.  The payload is zlib-deflated; after decompression:
//   uint32 script_len, input_num, table_off, string_off
//   input_num * 8 bytes of (count, start) pairs
//   ((string_off - table_off) / 4) uint32 line offsets
//   line strings: uint16 type + cp932 bytes + NUL

enum class SceneLineType : std::uint16_t {
    NONE = 0,
    INPUT = 0x0201,
    PAGE = 0x0301,
    MESSAGE = 0x2001,
    NAME = 0x2101,
    COMMAND = 0x3001,
};

// Enum name for a known kind, else the raw "0xNNNN" form.
std::string scene_line_type_name(std::uint16_t kind);

struct SceneLine {
    int idx = 0;
    std::uint16_t kind = 0;
    std::string content;  // UTF-8
};

class SceneScript {
public:
    explicit SceneScript(const Bytes& data);
    const std::vector<SceneLine>& lines() const { return lines_; }

private:
    std::vector<SceneLine> lines_;
};

}  // namespace ama::cs2
